

#Disable Warning IDE1006 ' Naming Styles
Imports System.ComponentModel
'------------------------------------------------------------
'-                File Name : clsShape                     - 
'-                Part of Project: Assign6                  -
'------------------------------------------------------------
'-                Written By: Nathan Gaffney                -
'-                Written On: 20 Feb 2020                   -
'------------------------------------------------------------
'- File Purpose:                                            -
'- This file contains the event handlers for MDI parent     -
'- the majorit of this file is auto generated by Visual     -
'- Studio when creating a mdi parent form                   -
'------------------------------------------------------------	
Public Class frmMDIParent
#Enable Warning IDE1006 ' Naming Styles
    '------------------------------------------------------------
    '-                Subprogram Name: btnPutNumberIntoText     -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing mnuFileNew       -
    '- iot will create a new child form                         -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- ChildForm - then new childform being made                -
    '------------------------------------------------------------
    Private Sub ShowNewForm(ByVal sender As Object, ByVal e As EventArgs) Handles mnuFileNew.Click
        ' Create a new instance of the child form.
        ' Make it a child of this MDI form before showing it.
        Dim ChildForm As New frmChild With {
            .MdiParent = Me
        }

        m_ChildFormNumber += 1
        ChildForm.Text = "Window " & m_ChildFormNumber

        ChildForm.Show()
    End Sub
    '------------------------------------------------------------
    '-        Subprogram Name: ExitToolsStripMenuItem_Click     -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing mnuFileExit      -
    '- it will close the mdi parent                             -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub ExitToolsStripMenuItem_Click(ByVal sender As Object, ByVal e As EventArgs) Handles mnuFileExit.Click
        Me.Close()
    End Sub
    '------------------------------------------------------------
    '-        Subprogram Name: CascadeToolStripMenuItem_Click   -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing mnuWindowsCascade-
    '- it set teh layout to cascade                             -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub CascadeToolStripMenuItem_Click(ByVal sender As Object, ByVal e As EventArgs) Handles mnuWindowsCascade.Click
        Me.LayoutMdi(MdiLayout.Cascade)
    End Sub
    '------------------------------------------------------------
    '-   Subprogram Name: TileVerticalToolStripMenuItem_Click   -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing                  -
    '- mnuWindowsTileVertical- it set the layout to vertical    -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub TileVerticalToolStripMenuItem_Click(ByVal sender As Object, ByVal e As EventArgs) Handles mnuWindowsTileVertical.Click
        Me.LayoutMdi(MdiLayout.TileVertical)
    End Sub
    '------------------------------------------------------------
    '-   Subprogram Name: TileHorizontalToolStripMenuItem_Click -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing                  -
    '- mnuWindowsTileHorizantal it set the layout to tile       -
    '- horizantal                                               -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub TileHorizontalToolStripMenuItem_Click(ByVal sender As Object, ByVal e As EventArgs) Handles mnuWindowsTileHorizantal.Click
        Me.LayoutMdi(MdiLayout.TileHorizontal)
    End Sub
    '------------------------------------------------------------
    '-        Subprogram Name: closeForm                        -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when mdi parent is closing     -
    '- it willloop through all children and close trigger their -
    '- closing method                                           -
    '- Currently causes a duplicate call to close, I do not know-
    '- why.
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub closeForm(ByVal sender As Object, ByVal e As EventArgs) Handles mnuWindowsCloseAll.Click, Me.Closing
        ' Close all child forms of the parent.
        For Each ChildForm As Form In Me.MdiChildren
            ChildForm.Close()
        Next
    End Sub

    Private m_ChildFormNumber As Integer
    '------------------------------------------------------------
    '-        Subprogram Name: AboutToolStripMenuItem_Click     -
    '------------------------------------------------------------
    '-                Written By: Nathan Gaffney                -
    '-                Written On: 20 Feb 2020                   -
    '------------------------------------------------------------
    '- Subprogram Purpose:                                      -
    '-                                                          -
    '- This subroutine is called when pressing mnuAbout         -
    '- it will open the about form for the project              -
    '------------------------------------------------------------
    '- Parameter Dictionary (in parameter order):               -
    '- sender - the object calling the event handler            -
    '- e - event arguments                                      -
    '------------------------------------------------------------
    '- Local Variable Dictionary (alphabetically):              -
    '- (None)                                                   -
    '------------------------------------------------------------
    Private Sub AboutToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles mnuAbout.Click
        frmAbout.ShowDialog()
    End Sub
End Class
